services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

  postgres:
    image: postgres:latest
    container_name: app-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U conta -d mydatabase']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
